#!/usr/bin/env bash
set -euo pipefail

export HOTWEIGHTS_IPC_COPY_AUTOTUNE=0
export HOTWEIGHTS_IPC_COPY_CHUNK_MB=${HOTWEIGHTS_IPC_COPY_CHUNK_MB:-8}
export HOTWEIGHTS_IPC_COPY_STREAMS=${HOTWEIGHTS_IPC_COPY_STREAMS:-2}
export HOTWEIGHTS_IPC_INFLIGHT_BUCKETS=${HOTWEIGHTS_IPC_INFLIGHT_BUCKETS:-3}
export HOTWEIGHTS_IPC_ADAPT=${HOTWEIGHTS_IPC_ADAPT:-1}
export HOTWEIGHTS_IPC_MIN_INFLIGHT=${HOTWEIGHTS_IPC_MIN_INFLIGHT:-1}
export HOTWEIGHTS_IPC_MAX_INFLIGHT=${HOTWEIGHTS_IPC_MAX_INFLIGHT:-6}
export HOTWEIGHTS_IPC_TARGET_BUCKET_MS=${HOTWEIGHTS_IPC_TARGET_BUCKET_MS:-350}

echo "Applied PCIe preset (copy ${HOTWEIGHTS_IPC_COPY_CHUNK_MB}MB/${HOTWEIGHTS_IPC_COPY_STREAMS} streams, window ${HOTWEIGHTS_IPC_INFLIGHT_BUCKETS}, adapt ${HOTWEIGHTS_IPC_ADAPT})."

