#!/usr/bin/env bash
set -euo pipefail

export HOTWEIGHTS_COORD_BACKEND=${HOTWEIGHTS_COORD_BACKEND:-redis}
export HOTWEIGHTS_REDIS_URL=${HOTWEIGHTS_REDIS_URL:-redis://127.0.0.1:6379/0}
export HOTWEIGHTS_HANDLE_TTL=${HOTWEIGHTS_HANDLE_TTL:-45}

echo "Applied Redis HA preset (backend=$HOTWEIGHTS_COORD_BACKEND url=$HOTWEIGHTS_REDIS_URL ttl=$HOTWEIGHTS_HANDLE_TTL)."

