#!/usr/bin/env bash
set -euo pipefail

export HOTWEIGHTS_IPC_COPY_AUTOTUNE=${HOTWEIGHTS_IPC_COPY_AUTOTUNE:-1}
export HOTWEIGHTS_IPC_COPY_CHUNK_MB=${HOTWEIGHTS_IPC_COPY_CHUNK_MB:-64}
export HOTWEIGHTS_IPC_COPY_STREAMS=${HOTWEIGHTS_IPC_COPY_STREAMS:-4}
export HOTWEIGHTS_IPC_INFLIGHT_BUCKETS=${HOTWEIGHTS_IPC_INFLIGHT_BUCKETS:-6}
export HOTWEIGHTS_IPC_ADAPT=${HOTWEIGHTS_IPC_ADAPT:-1}
export HOTWEIGHTS_IPC_MIN_INFLIGHT=${HOTWEIGHTS_IPC_MIN_INFLIGHT:-2}
export HOTWEIGHTS_IPC_MAX_INFLIGHT=${HOTWEIGHTS_IPC_MAX_INFLIGHT:-12}
export HOTWEIGHTS_IPC_TARGET_BUCKET_MS=${HOTWEIGHTS_IPC_TARGET_BUCKET_MS:-200}
# Optional
export HOTWEIGHTS_USE_GDS=${HOTWEIGHTS_USE_GDS:-0}

echo "Applied NVLink preset (copy ${HOTWEIGHTS_IPC_COPY_CHUNK_MB}MB/${HOTWEIGHTS_IPC_COPY_STREAMS} streams, window ${HOTWEIGHTS_IPC_INFLIGHT_BUCKETS}, adapt ${HOTWEIGHTS_IPC_ADAPT})."

