name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
      - name: Lint (ruff)
        continue-on-error: true
        run: |
          ruff --version
          ruff check .
      - name: Format check (black)
        continue-on-error: true
        run: |
          black --version
          black --check .
      - name: Run tests (CPU-only markers)
        env:
          PYTHONWARNINGS: default
        run: |
          pytest -m "not slow and not gpu and not mpi" -q
